//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoStatesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Of_Living
    {
        public int C_ID { get; set; }
        public Nullable<long> Public_Transport { get; set; }
        public Nullable<long> Food { get; set; }
        public Nullable<long> Rent_Allowances { get; set; }
        public Nullable<int> C_Cities { get; set; }
    
        public virtual city city { get; set; }
    }
}
