//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoStatesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int E_ID { get; set; }
        public string Event_Name { get; set; }
        public Nullable<System.DateTime> Event_Date { get; set; }
        public string E_Categorytype { get; set; }
        public Nullable<int> E_Cities { get; set; }
        public Nullable<int> E_user { get; set; }
    
        public virtual city city { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
