//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoStatesDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TwoStates1Entities : DbContext
    {
        public TwoStates1Entities()
            : base("name=TwoStates1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<Cost_Of_Living> Cost_Of_Living { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Population> Populations { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<Tourism> Tourism { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
    }
}
