//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoStatesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int T_ID { get; set; }
        public Nullable<bool> Metro_Services { get; set; }
        public Nullable<bool> Local_trains { get; set; }
        public Nullable<bool> Local_buses { get; set; }
        public Nullable<bool> Flights { get; set; }
        public Nullable<bool> Cab_Services { get; set; }
        public Nullable<int> T_Cities { get; set; }
    
        public virtual city city { get; set; }
    }
}
