//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwoStatesDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Details()
        {
            this.Events = new HashSet<Event>();
            this.Languages = new HashSet<Language>();
            this.Tourism = new HashSet<Tourism>();
        }
    
        public int User_ID { get; set; }
        public string User_Type { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> Phoneno { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Email_Verified { get; set; }
        public string Password { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Subscribe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language> Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tourism> Tourism { get; set; }
    }
}
